version: '3.1'

services:

  nessus:
    image: tenableofficial/nessus
    restart: always
    container_name: nessus
    environment:
      USERNAME: mahato1456
      PASSWORD: Anil@3270
      ACTIVATION_CODE: 123456
    ports:
      - 8834:8834
